# Generated by Django 5.1.6 on 2025-02-05 22:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
        ('subjects', '0002_subject_prerequisitos_alter_subject_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student_id', 'subject_id')},
        ),
    ]
