# Generated by Django 5.1.6 on 2025-02-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_registration_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='final_rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
