# Generated by Django 5.1.6 on 2025-02-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='prerequisitos',
            field=models.ManyToManyField(blank=True, related_name='materias_dependientes', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
