# Generated by Django 5.1.6 on 2025-02-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
